// import httpBase from "@/service/httpBase";

export const getInspirations = async () => {
    // await httpBase.post(`/inspirations`, {
    //     imageid: 0,
    //     mode: "GetInspirationsList",
    // });
    return [
        {
            id: 1,
            sellerid: null,
            title: "Dining Table",
            details: null,
            image: "/pinimages/1.png",
            destinationurl:
                "https://www.buyamia.com/productdetail/Furniture/Furniture/-Dining-Table-Radja-Rustic-top-7cm-1978",
            filetype: "I",
            categoryid: 3,
        },
        {
            id: 2,
            sellerid: null,
            title: "Table Drawer",
            details: null,
            image: "/pinimages/2.png",
            destinationurl: "https://www.buyamia.com/categorynew/3-51",
            filetype: "I",
            categoryid: 3,
        },
        {
            id: 3,
            sellerid: null,
            title: "Night Lamps",
            details: null,
            image: "/pinimages/3.png",
            destinationurl: "https://www.buyamia.com/category/0?searchbar=lamp",
            filetype: "I",
            categoryid: 4,
        },
        {
            id: 5,
            sellerid: null,
            title: "Shelf & Sofa",
            details: null,
            image: "/pinimages/4.png",
            destinationurl: "https://www.buyamia.com/categorynew/3-51",
            filetype: "I",
            categoryid: 3,
        },
        {
            id: 6,
            sellerid: null,
            title: "Antique Drawers",
            details: null,
            image: "/pinimages/5.png",
            destinationurl: "https://www.buyamia.com/categorynew/3-51",
            filetype: "I",
            categoryid: 1,
        },
        {
            id: 7,
            sellerid: null,
            title: "Bowl Arts",
            details: null,
            image: "/pinimages/6.png",
            destinationurl: "https://www.buyamia.com/category/0?searchbar=bowl",
            filetype: "I",
            categoryid: 4,
        },
        {
            id: 9,
            sellerid: null,
            title: "Lights & Lamps",
            details: null,
            image: "/pinimages/8.png",
            destinationurl: "https://www.buyamia.com/category/0?searchbar=lamp",
            filetype: "I",
            categoryid: 4,
        },
        {
            id: 10,
            sellerid: null,
            title: "King Chair",
            details: null,
            image: "/pinimages/9.png",
            destinationurl:
                "https://www.buyamia.com/category/0?searchbar=chair",
            filetype: "I",
            categoryid: 3,
        },
        {
            id: 11,
            sellerid: null,
            title: "Arts",
            details: null,
            image: "/pinimages/10.png",
            destinationurl: "https://www.buyamia.com/categorynew/1",
            filetype: "I",
            categoryid: 1,
        },
        {
            id: 12,
            sellerid: null,
            title: "Arts",
            details: null,
            image: "/pinimages/11.png",
            destinationurl: "https://www.buyamia.com/categorynew/1",
            filetype: "I",
            categoryid: 1,
        },
        {
            id: 13,
            sellerid: null,
            title: "Arts (Hand Made)",
            details: null,
            image: "/pinimages/12.png",
            destinationurl:
                "https://www.buyamia.com/category/0?searchbar=sculpture",
            filetype: "I",
            categoryid: 1,
        },
        {
            id: 14,
            sellerid: null,
            title: "Jewelry",
            details: null,
            image: "/pinimages/13.png",
            destinationurl:
                "https://www.buyamia.com/categorynew/jewelry---accessories/necklaces/7-57",
            filetype: "I",
            categoryid: 1,
        },
        {
            id: 16,
            sellerid: null,
            title: "Arts",
            details: null,
            image: "/pinimages/14.png",
            destinationurl: "https://www.buyamia.com/categorynew/1",
            filetype: "I",
            categoryid: 1,
        },
        {
            id: 23,
            sellerid: null,
            title: "Hand Bag",
            details: null,
            image: "/pinimages/15.png",
            destinationurl: "https://www.buyamia.com/categorynew/1",
            filetype: "I",
            categoryid: 1,
        },
        {
            id: 24,
            sellerid: null,
            title: "Arts",
            details: null,
            image: "/pinimages/16.png",
            destinationurl: "https://www.buyamia.com/categorynew/1",
            filetype: "I",
            categoryid: 1,
        },
        {
            id: 25,
            sellerid: null,
            title: "Hand Bag",
            details: null,
            image: "/pinimages/17.png",
            destinationurl: "https://www.buyamia.com/categorynew/1",
            filetype: "I",
            categoryid: 1,
        },
        {
            id: 26,
            sellerid: null,
            title: "Arts",
            details: null,
            image: "/pinimages/18.png",
            destinationurl: "https://www.buyamia.com/categorynew/1",
            filetype: "I",
            categoryid: 1,
        },
        {
            id: 31,
            sellerid: null,
            title: "How I made it",
            details: null,
            image: "/pinvideos/1.mp4",
            destinationurl: "https://www.buyamia.com/categorynew/4",
            filetype: "V",
            categoryid: 4,
        },
        {
            id: 32,
            sellerid: null,
            title: "Furniture",
            details: null,
            image: "/pinvideos/3.mp4",
            destinationurl: "https://www.buyamia.com/categorynew/3-51",
            filetype: "V",
            categoryid: 3,
        },
        {
            id: 33,
            sellerid: null,
            title: "Beauty",
            details: null,
            image: "/pinvideos/2.mp4",
            destinationurl: "https://www.buyamia.com/categorynew/2",
            filetype: "V",
            categoryid: 2,
        },
        {
            id: 43,
            sellerid: 373,
            title: "This is a Video Test",
            details: "video",
            image: "https://buyamia-seller-media.s3.ap-south-1.amazonaws.com/Images/ssshop/373/samplevideo_1280x720_2mb.mp4",
            destinationurl:
                "https://buyamia-seller-media.s3.ap-south-1.amazonaws.com/Images/ssshop/373/samplevideo_1280x720_2mb.mp4",
            filetype: "V",
            categoryid: null,
        },
        {
            id: 408,
            sellerid: null,
            title: "DAMAR LONTAR Hanging Lamp",
            details: null,
            image: "https://buyamia-media.s3.ap-south-1.amazonaws.com/Images/1/product/1658748900512_.jpg",
            destinationurl: "https://www.buyamia.com/product/408",
            filetype: "I",
            categoryid: 4,
        },
        {
            id: 628,
            sellerid: null,
            title: "Long Loungewear Model 2",
            details: null,
            image: "https://buyamia-media.s3.ap-south-1.amazonaws.com/Images/432/product/1644973314095_.jpeg",
            destinationurl: "https://www.buyamia.com/product/628",
            filetype: "I",
            categoryid: 5,
        },
        {
            id: 651,
            sellerid: null,
            title: "Black Cone Pendant",
            details: null,
            image: "https://buyamia-media.s3.ap-south-1.amazonaws.com/Images/460/product/1645167937012_.jpeg",
            destinationurl: "https://www.buyamia.com/product/651",
            filetype: "I",
            categoryid: 4,
        },
        {
            id: 660,
            sellerid: null,
            title: "Keong Rotan",
            details: null,
            image: "https://buyamia-media.s3.ap-south-1.amazonaws.com/Images/460/product/1645417301171_.jpeg",
            destinationurl: "https://www.buyamia.com/product/660",
            filetype: "I",
            categoryid: 4,
        },
        {
            id: 662,
            sellerid: null,
            title: "Pendant Bamboo/rattan",
            details: null,
            image: "https://buyamia-media.s3.ap-south-1.amazonaws.com/Images/460/product/1645423745756_.jpeg",
            destinationurl: "https://www.buyamia.com/product/662",
            filetype: "I",
            categoryid: 4,
        },
        {
            id: 663,
            sellerid: null,
            title: "Moroccan Pendant Dome Jig-Jag Lamp Shade",
            details: null,
            image: "https://buyamia-media.s3.ap-south-1.amazonaws.com/Images/460/product/1645426893859_.jpeg",
            destinationurl: "https://www.buyamia.com/product/663",
            filetype: "I",
            categoryid: 4,
        },
        {
            id: 671,
            sellerid: null,
            title: "Necklace gem stone 3 mm",
            details: null,
            image: "https://buyamia-media.s3.ap-south-1.amazonaws.com/Images/530/product/1647936332426_.jpeg",
            destinationurl: "https://www.buyamia.com/product/671",
            filetype: "I",
            categoryid: 7,
        },
        {
            id: 679,
            sellerid: null,
            title: "Wooden Sunglasses ",
            details: null,
            image: "https://buyamia-media.s3.ap-south-1.amazonaws.com/Images/342/product/1646090160277_.jpeg",
            destinationurl: "https://www.buyamia.com/product/679",
            filetype: "I",
            categoryid: 7,
        },
        {
            id: 786,
            sellerid: null,
            title: "Cotton Orange Dandelion Flower Cushion Cover",
            details: null,
            image: "https://buyamia-media.s3.ap-south-1.amazonaws.com/Images/524/product/1646889502729_.jpeg",
            destinationurl: "https://www.buyamia.com/product/786",
            filetype: "I",
            categoryid: 4,
        },
        {
            id: 835,
            sellerid: null,
            title: "MACRAME KAP Lamp",
            details: null,
            image: "https://buyamia-media.s3.ap-south-1.amazonaws.com/Images/575/product/1646992084740_.jpeg",
            destinationurl: "https://www.buyamia.com/product/835",
            filetype: "I",
            categoryid: 4,
        },
        {
            id: 996,
            sellerid: null,
            title: "Barn Standing Wooden Goat Statue Table Decoration",
            details: null,
            image: "https://buyamia-media.s3.ap-south-1.amazonaws.com/Images/555/product/1649912968697_.jpeg",
            destinationurl: "https://www.buyamia.com/product/996",
            filetype: "I",
            categoryid: 4,
        },
        {
            id: 1084,
            sellerid: null,
            title: "Blue Jalli Handbag",
            details: null,
            image: "https://buyamia-media.s3.ap-south-1.amazonaws.com/Images/563/product/1647332683317_.jpeg",
            destinationurl: "https://www.buyamia.com/product/1084",
            filetype: "I",
            categoryid: 7,
        },
        {
            id: 1086,
            sellerid: null,
            title: "Orange and Nude Jalli Handbag",
            details: null,
            image: "https://buyamia-media.s3.ap-south-1.amazonaws.com/Images/563/product/1647332907751_.jpeg",
            destinationurl: "https://www.buyamia.com/product/1086",
            filetype: "I",
            categoryid: 7,
        },
        {
            id: 1088,
            sellerid: null,
            title: "Turquoise Jalli Handbag ",
            details: null,
            image: "https://buyamia-media.s3.ap-south-1.amazonaws.com/Images/563/product/1647333119245_.jpeg",
            destinationurl: "https://www.buyamia.com/product/1088",
            filetype: "I",
            categoryid: 7,
        },
        {
            id: 1090,
            sellerid: null,
            title: "White Jalli Handbag",
            details: null,
            image: "https://buyamia-media.s3.ap-south-1.amazonaws.com/Images/563/product/1647333305063_.jpeg",
            destinationurl: "https://www.buyamia.com/product/1090",
            filetype: "I",
            categoryid: 7,
        },
    ];
};


    